---
- block:
  - name: install virtualenv
    pip:
      name: virtualenv
      state: "{{ virtualenv_pip_state }}"
      version: "{{ virtualenv_pip_version | default(omit) }}"
      
  become: yes
  become_method: sudo
  tags:
    - virtualenv_pip
